### ISSUE TITLE
No such file or directory 'coverage-summary.json'

### ISSUE THREAD

**Issue by kouchao** [sidx1024/coverage-reporter-action#29]
Error: ENOENT: no such file or directory, open '/home/runner/work/TiantianFundApi/TiantianFundApi/coverage-summary.json'
![image](https://user-images.githubusercontent.com/23720738/170841362-3bd1d63a-4bd0-4183-8f2a-bd5663e62f66.png)

**Comment by sidx1024** [comment]
Hi @kouchao, thanks for reporting this issue. The example in the readme was incorrect (the pinned version was outdated). It has now been updated.
